---
- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400

    - name: Install base packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      vars:
        packages:
        - build-essential
        - libssl-dev
        - libffi-dev
        - vim
        - git
        - htop
        - jq
        - python3-dev
        - python3-pip
        - python-setuptools
        - python3-virtualenv
        - python3-venv
        - python3-pytest
        - pylint3
        - black
        - flake8
    - name: Install python modules with pip
      pip:
        name: "{{ modules }}"
        executable: "/usr/bin/pip3"
      vars:
        modules:
        - poetry
        - ipython
    - name: Add Python Path to bashrc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: export PYTHONPATH=:/vagrant